[project]
name = "text-search"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.1.0",
    "numpy>=2.3.3",
    "pymupdf>=1.26.4",
    "pypdf2>=3.0.1",
    "requests>=2.32.5",
]
